[package]
name = "gkr"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ff.workspace = true
ark-std.workspace = true
goldilocks.workspace = true

simple-frontend = { path = "../simple-frontend" }
transcript = { path = "../transcript" }
sumcheck = { path = "../sumcheck" }
multilinear_extensions = { path = "../multilinear_extensions" }
itertools = "0.12.0"
serde.workspace = true
serde_json = "1.0.108"
rayon.workspace = true
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tracing-flame = "0.2.0"
tracing = "0.1.40"

[dev-dependencies]
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
pprof = { version = "0.13", features = ["flamegraph"]}
criterion = { version = "0.5", features = ["html_reports"] }
cfg-if = "1.0.0"

[features]
default = [ ]
flamegraph = ["pprof/flamegraph", "pprof/criterion"]
parallel = [ ]
unsafe = [ ]

[[bench]]
name = "keccak256"
harness = false
