[workspace]
members = [
    "ceno_emul",
    "gkr",
    "gkr-graph",
    "mpcs",
    "multilinear_extensions",
    "simple-frontend",
    "singer",
    "singer-pro",
    "singer-utils",
    "sumcheck",
    "transcript",
    "ceno_zkvm"
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
ark-std = { version = "0.4" }
# ark-std = { version = "0.4", features = ["print-trace"] }
ark-poly = "0.4"
criterion = { version = "0.5", features = ["html_reports"] }
ff = "0.13"
goldilocks = { git = "https://github.com/zhenfeizhang/Goldilocks" }
halo2curves = "0.1.0"
poseidon = { git = "https://github.com/zhenfeizhang/poseidon" }
serde = { version = "1.0", features = ["derive"] }
subtle = "2.2.1"
rand_core = "0.6.0"
rand_xorshift = "0.3"
rayon = "1.8"

[patch."https://github.com/zhenfeizhang/Goldilocks"]
goldilocks = { git = "https://github.com/hero78119/Goldilocks" }
